Repository mkrumholz/viewing_party, pull requests merged in 2021-07, with the labels that each got.

#21 (TEST) Update welcome message
  app/views/welcome/index.html.erb
Labels: test

#22 Complete Registration and Login functionality
  .travis.yml
  Gemfile
  Gemfile.lock
  app/controllers/users_controller.rb
  app/controllers/welcome_controller.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/users/login_form.html.erb
  app/views/users/new.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  db/migrate/20210706204156_create_users.rb
  db/schema.rb
  spec/features/login_spec.rb
  spec/features/welcome_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
Labels: Core, chore

#23 Create log out functionality and refactor for ReSTful sessions routes
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/controllers/welcome_controller.rb
  app/models/user.rb
  app/views/sessions/new.html.erb
  app/views/users/new.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/logout_spec.rb
  spec/features/welcome_spec.rb
Labels: Core, enhancement

#24 Dashboard
  app/controllers/dashboard_controller.rb
  app/controllers/discover_controller.rb
  app/controllers/friendships_controller.rb
  app/models/friendship.rb
  app/models/user.rb
  app/views/dashboard/show.html.erb
  app/views/discover/index.html.erb
  config/routes.rb
  db/migrate/20210708235359_create_friends.rb
  db/migrate/20210709000742_change_friends_to_friendships.rb
  db/schema.rb
  spec/features/dashboard_spec.rb
  spec/models/friendship_spec.rb
  spec/models/user_spec.rb
Labels: Core

#30 Refactoring
  Gemfile.lock
  app/controllers/discover_controller.rb
  app/controllers/friendships_controller.rb
  app/controllers/movies_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/users/show.html.erb
  config/routes.rb
  spec/features/dashboard_spec.rb
  spec/models/user_spec.rb
  spec/spec_helper.rb
Labels: refactor

#31 Movie view page
  app/controllers/movies_controller.rb
  app/poros/movie.rb
  app/services/movie_db_service.rb
  app/views/movies/index.html.erb
  app/views/movies/show.html.erb
  config/routes.rb
  spec/features/movies/index_spec.rb
  spec/features/movies/show_spec.rb
  spec/fixtures/toy_story.json
  spec/poros/movie_spec.rb
  spec/services/movie_db_service_spec.rb
Labels: API consumption

#36 Add functionality for sending emails to party guests
  app/mailers/application_mailer.rb
  app/mailers/invitation_mailer.rb
  app/models/party.rb
  app/views/invitation_mailer/invite.html.erb
  spec/mailers/invitation_spec.rb
  spec/mailers/previews/invitation_preview.rb
  spec/models/party_spec.rb
Labels: exploration

#39 Repair party bug
  app/controllers/users/parties_controller.rb
Labels: bug

#43 Refactor Parties to store date/time in a single column
  app/controllers/application_controller.rb
  app/controllers/users/parties_controller.rb
  app/models/party.rb
  app/views/invitation_mailer/invite.html.erb
  app/views/users/parties/new.html.erb
  app/views/users/show.html.erb
  db/migrate/20210715234519_change_datatype_for_date.rb
  db/migrate/20210715234605_remove_time_from_parties.rb
  db/migrate/20210715234724_change_date_to_starts_at.rb
  db/schema.rb
  spec/features/parties/dashboard_party_spec.rb
  spec/features/parties/new_party_spec.rb
  spec/mailers/invitation_spec.rb
  spec/models/invitation_spec.rb
  spec/models/party_spec.rb
Labels: refactor
